// src/components/BatteryLegend.svelte
<script>
  import { FC } from "@/js/fc.svelte.js";

  const NO_BATTERY_VOLTAGE_MAXIMUM = 1.8;

  let value = $derived.by(() => {
    const voltage = FC.BATTERY_STATE.voltage.toFixed(2);
    const cells =
      FC.BATTERY_STATE.voltage > NO_BATTERY_VOLTAGE_MAXIMUM
        ? `${FC.BATTERY_STATE.cellCount}S`
        : "USB";

    return `${voltage}V (${cells})`;
  });
</script>

{value}

// src/components/quad-status/BatteryLegend.vue
<template>
  <div class="battery-legend">
    {{ reading }}
  </div>
</template>
<script>
const NO_BATTERY_VOLTAGE_MAXIMUM = 1.8;

export default {
  props: {
    voltage: {
      type: Number,
      default: 0,
    },
    cellcount: {
      type: Number,
      default: 0,
    },
  },
  computed: {
    reading() {
      const cellsText =
        this.voltage > NO_BATTERY_VOLTAGE_MAXIMUM ? `${this.cellcount}S` : "USB";
      return `${this.voltage.toFixed(2)}V (${cellsText})`;
    },
  },
};
</script>
